---
name: Run automatic tests
on:
  pull_request:
    branches:
      - main
jobs:
  run_automatic_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -

      - name: Install dependencies
        working-directory: .
        run: poetry install

      - name: Make sure browsers are installed for Playwright
        run: poetry run playwright install --with-deps

      - name: Start local server for testing
        run: poetry run python app.py &

      - name: Run tests
        run: poetry run pytest app.py
        continue-on-error: false